repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files # Prevent giant files from being committed. (default=500kB).
    -   id: check-toml # Attempts to load all TOML files to verify syntax.
    -   id: check-yaml # Attempts to load all yaml files to verify syntax.
        args:
        -   --unsafe #  Instead of loading the files, simply parse them for syntax.
    -   id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
    -   id: trailing-whitespace # Trims trailing whitespace.
        args:
        - --markdown-linebreak-ext=md # preserve Markdown hard linebreaks

  # pyupgrade - automatically upgrade syntax for newer versions of the language
  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
      -   id: pyupgrade

  # ruff - an extremly fast Python linter
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.239'
    hooks:
      - id: ruff

  # Black - the Uncompromising Code Formatter
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black
